spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicio_autenticacion
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: eduplanerr@gmail.com
    password: xogu ovkh uxdb bgll
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 3306
  servlet:
    context-path: /eduplanner/

jwt:
  secret-key: rf4LsNMmsMosdnDPYvOu41z0ExY2HYjuY83Ep9QDT5s=
  token-expiration: 600000 # 10 min en ms
