wrapperVersion=3.3.4
distributionType=only-script
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.15/apache-maven-3.9.15-bin.zip
=======
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
>>>>>>> 633bf15418da8912c0adc101aca3fba33ec57b3e
