spring:
  application:
    name: ed-ms-gestion-academica

  datasource:
    url: jdbc:mysql://localhost:3306/academic_management
    username: root
    password: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083
  servlet:
    context-path: /eduplanner/

security:
  jwt:
    secret-key: czyYSEj017tCB8M8mnOSvhgV4gSdI4P5Bql+3HrWZtM=

services: 
  administracion:
    base-url: http://localhost:8082/eduplanner
