spring:
  application:
    name: ed_ms_notas

  cloud:
    consul:
      host: localhost
      port: 8500

      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /eduplanner/actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never