spring:
  application:
    name: ed_ms_notas 

  datasource:
    url: jdbc:mysql://localhost:3306/microNotes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

server:
  port: 8084
  servlet:
    context-path: /eduplanner/

security:
  jwt:
    secret-key: czyYSEj017tCB8M8mnOSvhgV4gSdI4P5Bql+3HrWZtM=

services: 
  administracion:
    base-url: http://localhost:8084/eduplanner
  gestion-academica:
    base-url: http://localhost:8083/eduplanner
